[2024-05-31T12:07:01.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T12:07:02.011+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__3 manual__2024-05-31T12:06:28.682787+00:00 [queued]>
[2024-05-31T12:07:02.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__3 manual__2024-05-31T12:06:28.682787+00:00 [queued]>
[2024-05-31T12:07:02.016+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T12:07:02.025+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__3> on 2024-05-31 12:06:28.682787+00:00
[2024-05-31T12:07:02.030+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=764) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T12:07:02.031+0000] {standard_task_runner.py:63} INFO - Started process 773 to run task
[2024-05-31T12:07:02.031+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__3', 'manual__2024-05-31T12:06:28.682787+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp668tn_om']
[2024-05-31T12:07:02.033+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask load_data__3
[2024-05-31T12:07:02.063+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__3 manual__2024-05-31T12:06:28.682787+00:00 [running]> on host e5f19cf3157d
[2024-05-31T12:07:02.179+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__3' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T12:06:28.682787+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T12:06:28.682787+00:00'
[2024-05-31T12:07:02.180+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T12:07:02.180+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T12:07:02.181+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T12:07:04.806+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T12:07:04.806+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T12:07:04.813+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__3, run_id=manual__2024-05-31T12:06:28.682787+00:00, execution_date=20240531T120628, start_date=20240531T120702, end_date=20240531T120704
[2024-05-31T12:07:04.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T12:07:04.865+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T12:07:04.866+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
