[2024-06-13T08:59:20.654+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T08:59:20.674+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:59:19.027492+00:00 [queued]>
[2024-06-13T08:59:20.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:59:19.027492+00:00 [queued]>
[2024-06-13T08:59:20.681+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T08:59:20.694+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_elt_dag> on 2024-06-13 08:59:19.027492+00:00
[2024-06-13T08:59:20.699+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1016) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T08:59:20.700+0000] {standard_task_runner.py:63} INFO - Started process 1025 to run task
[2024-06-13T08:59:20.701+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'wait_for_elt_dag', 'manual__2024-06-13T08:59:19.027492+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpu0emvd5v']
[2024-06-13T08:59:20.703+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask wait_for_elt_dag
[2024-06-13T08:59:20.748+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:59:19.027492+00:00 [running]> on host c97498906c69
[2024-06-13T08:59:20.818+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='wait_for_elt_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T08:59:19.027492+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T08:59:19.027492+00:00'
[2024-06-13T08:59:20.819+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T08:59:20.819+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-13T08:59:20.820+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T08:59:20.820+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-13T09:00:20.828+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:01:20.836+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:02:20.845+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:03:20.852+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:04:20.860+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:05:20.867+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:06:20.874+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:07:20.882+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:08:20.895+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:09:20.902+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:59:19.027492+00:00 ... 
[2024-06-13T09:09:20.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:09:20.914+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.0939735340071 seconds exceeds the specified timeout of 600.0.
[2024-06-13T09:09:20.922+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=wait_for_elt_dag, run_id=manual__2024-06-13T08:59:19.027492+00:00, execution_date=20240613T085919, start_date=20240613T085920, end_date=20240613T090920
[2024-06-13T09:09:20.932+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task wait_for_elt_dag (Sensor has timed out; run duration of 600.0939735340071 seconds exceeds the specified timeout of 600.0.; 1025)
[2024-06-13T09:09:20.949+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T09:09:20.961+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:09:20.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
