[2024-06-06T09:17:13.363+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T09:44:10.016+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T09:47:38.870+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T09:53:40.955+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T10:22:21.000+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T10:36:17.821+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T10:44:01.798+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T10:54:12.355+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T11:58:01.731+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T12:32:05.411+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T12:40:22.436+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T12:44:58.011+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T12:49:20.226+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T12:54:07.327+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T13:05:50.742+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:23:03.258+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:28:03.846+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:31:44.477+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:35:10.314+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:38:38.042+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:44:23.102+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-06-06T14:54:41.493+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka scheduled__2024-06-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
