[2024-06-14T12:35:25.303+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T12:35:25.321+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-14T12:35:24.060229+00:00 [queued]>
[2024-06-14T12:35:25.326+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-14T12:35:24.060229+00:00 [queued]>
[2024-06-14T12:35:25.327+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T12:35:25.335+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_publish_dag> on 2024-06-14 12:35:24.060229+00:00
[2024-06-14T12:35:25.341+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2638) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-14T12:35:25.342+0000] {standard_task_runner.py:63} INFO - Started process 2647 to run task
[2024-06-14T12:35:25.343+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_kafka_consumeAndLoad', 'wait_for_publish_dag', 'manual__2024-06-14T12:35:24.060229+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/ergast_kafka_consume_and_load.py', '--cfg-path', '/tmp/tmpkinzkx25']
[2024-06-14T12:35:25.345+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask wait_for_publish_dag
[2024-06-14T12:35:25.381+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-14T12:35:24.060229+00:00 [running]> on host e4ecbb11494f
[2024-06-14T12:35:25.452+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_kafka_consumeAndLoad' AIRFLOW_CTX_TASK_ID='wait_for_publish_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T12:35:24.060229+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T12:35:24.060229+00:00'
[2024-06-14T12:35:25.453+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T12:35:25.453+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-14T12:35:25.454+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-14T12:35:24.060229+00:00 ... 
[2024-06-14T12:35:25.454+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-14T12:35:55.463+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-14T12:35:24.060229+00:00 ... 
[2024-06-14T12:36:25.470+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-14T12:35:24.060229+00:00 ... 
[2024-06-14T12:36:55.478+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-14T12:35:24.060229+00:00 ... 
[2024-06-14T12:37:25.485+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-14T12:35:24.060229+00:00 ... 
[2024-06-14T12:37:26.404+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-14T12:37:26.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T12:37:26.406+0000] {process_utils.py:132} INFO - Sending 15 to group 2647. PIDs of all processes in the group: [2647]
[2024-06-14T12:37:26.406+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2647
[2024-06-14T12:37:26.407+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-14T12:37:26.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T12:37:26.433+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2647, status='terminated', exitcode=0, started='12:35:24') (2647) terminated with exit code 0
