[2024-06-13T08:53:30.585+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T08:53:30.600+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:53:27.413408+00:00 [queued]>
[2024-06-13T08:53:30.605+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:53:27.413408+00:00 [queued]>
[2024-06-13T08:53:30.605+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T08:53:30.614+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_elt_dag> on 2024-06-13 08:53:27.413408+00:00
[2024-06-13T08:53:30.619+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=911) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T08:53:30.620+0000] {standard_task_runner.py:63} INFO - Started process 934 to run task
[2024-06-13T08:53:30.620+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'wait_for_elt_dag', 'manual__2024-06-13T08:53:27.413408+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmprgryzl0d']
[2024-06-13T08:53:30.622+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask wait_for_elt_dag
[2024-06-13T08:53:30.653+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-13T08:53:27.413408+00:00 [running]> on host c97498906c69
[2024-06-13T08:53:30.708+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='wait_for_elt_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T08:53:27.413408+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T08:53:27.413408+00:00'
[2024-06-13T08:53:30.709+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T08:53:30.709+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-13T08:53:30.709+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:53:30.710+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-13T08:54:30.717+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:55:30.729+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:56:30.741+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:57:30.747+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:58:30.759+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T08:59:30.771+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T09:00:30.781+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T09:01:30.789+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T09:02:30.799+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T09:03:30.807+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-13T08:53:27.413408+00:00 ... 
[2024-06-13T09:03:30.818+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T09:03:30.818+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.1084586429934 seconds exceeds the specified timeout of 600.0.
[2024-06-13T09:03:30.828+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=wait_for_elt_dag, run_id=manual__2024-06-13T08:53:27.413408+00:00, execution_date=20240613T085327, start_date=20240613T085330, end_date=20240613T090330
[2024-06-13T09:03:30.838+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 93 for task wait_for_elt_dag (Sensor has timed out; run duration of 600.1084586429934 seconds exceeds the specified timeout of 600.0.; 934)
[2024-06-13T09:03:30.852+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-13T09:03:30.863+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T09:03:30.865+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
